(ns leiningen.all
  (:require [leiningen.haml :as lhaml]
            [leiningen.sass :as lsass]
            [leiningen.scss :as lscss]
            [leiningen.help :as lhelp]
            [leiningen.lein-common.lein-utils :as lutils]))

(defn all
  "Compiles haml, sass, and scss files.
Subtasks available:
once    Compile all file types once
auto    Automatically recompiles when files are modified
clean   Removes the autogenerated files
"
  {:help-arglists '([:once :auto :clean])}
  ([project]
     (lutils/exit-failure (lhelp/help-for "all")))

  ([project subtask & args]
     (let [threads [(Thread. (fn [] (apply lhaml/haml project subtask args)))
                    (Thread. (fn [] (apply lsass/sass project subtask args)))
                    (Thread. (fn [] (apply lscss/scss project subtask args)))]]
       (doseq [t threads] (.start t))
       (doseq [t threads] (.join t)))))
