(ns leiningen.haml-sass
  (:require [leiningen.haml :as lhaml]
            [leiningen.sass :as lsass]
            [leiningen.scss :as lscss]
            [leiningen.help :as lhelp]
            [leiningen.lein-common.lein-utils :as lutils]))

(defn- create-thread-if-task [src-type task project subtask args]
  (when (src-type project)
    (Thread. (fn [] (apply task project subtask args)))))

(defn- all-tasks-to-run [project subtask args]
  (let [available-tasks {:haml lhaml/haml
                         :sass lsass/sass
                         :scss lscss/scss}]
    (keep (fn [[src-type task]]
            (create-thread-if-task src-type task project subtask args))
          available-tasks)))

;; Leiningen task
(defn haml-sass
  "Compiles haml, sass, and scss files.
Subtasks available:
once    Compile all file types once
auto    Automatically recompiles when files are modified
clean   Removes the autogenerated files
"
  {:help-arglists '([:once :auto :clean])}
  ([project]
     (lutils/exit-failure (lhelp/help-for "haml-sass")))

  ([project subtask & args]
     (let [threads (all-tasks-to-run project subtask args)]
       (doseq [t threads] (.start t))
       (doseq [t threads] (.join t)))))
