(ns leiningen.haml-sass
  (:require [leiningen.haml :as lhaml]
            [leiningen.sass :as lsass]
            [leiningen.help :as lhelp]
            [leiningen.lein-common.lein-utils :as lutils]))

(defn haml-sass
  "Compiles haml and sass files.
Subtasks available:
once    Compiles haml and sass files once
auto    Automatically recompiles when files are modified
clean   Removes the autogenerated files
"
  {:help-arglists '([:once :auto :clean])}
  ([project]
     (lutils/exit-failure (lhelp/help-for "haml-sass")))

  ([project subtask & args]
     (let [threads [(Thread. (fn [] (apply lhaml/haml project subtask args)))
                    (Thread. (fn [] (apply lsass/sass project subtask args)))]]
       (doseq [t threads] (.start t))
       (doseq [t threads] (.join t)))))
