(ns leiningen.sass
  (:use leiningen.lein-haml-sass.render-engine
        leiningen.lein-haml-sass.options
        leiningen.lein-common.lein-utils)
  (:require [leiningen.help    :as lhelp]
            [leiningen.clean   :as lclean]
            [leiningen.compile :as lcompile]
            [leiningen.deps    :as ldeps]
            [robert.hooke      :as hooke]))

(defn- once
  "Compiles the sass files once"
  [options]
  (println (str "Compiling sass files located in " (:src options)))
  (render-all! options false true))

(defn- auto
  "Automatically recompiles when files are modified"
  [options]
  (println (str "Ready to compile sass files located in " (:src options)))
  (flush)
  (render-all! options true))

(defn- clean
  "Removes the autogenerated files"
  [options]
  (println "Deleting files generated by lein-sass.")
  (clean-all! options))

(defn- deps
  "Installs the required sass gem"
  [options]
  (install-gem! options))

;; Leiningen tasks
(defn sass
  "Compiles sass files."
  {:help-arglists '([once auto clean])
   :subtasks [#'once #'auto #'clean #'deps]}
  ([project]
     (exit-failure (lhelp/help-for "sass")))

  ([project subtask & args]
     (let [options (extract-options :sass project)]
       (case subtask
         "once"  (once  options)
         "auto"  (auto  options)
         "clean" (clean options)
         "deps"  (deps  options)
         (task-not-found subtask)))))


;; Hooks stuffs
(defmacro hook [task subtask args]
  `(let [options# (extract-options :sass (first ~args))]
     (apply ~task ~args)
     (when-not (~subtask (:ignore-hooks options#))
       (~(symbol (name subtask)) options#))))

(defn- compile-hook [task & args]
  (hook task :once args))

(defn- clean-hook [task & args]
  (hook task :clean args))

(defn- deps-hook [task & args]
  (hook task :deps args))

(hooke/add-hook #'lcompile/compile #'compile-hook)
(hooke/add-hook #'lclean/clean #'clean-hook)
(hooke/add-hook #'ldeps/deps   #'deps-hook)
