(ns leiningen.scss
  (:use leiningen.lein-haml-sass.render-engine
        leiningen.lein-haml-sass.options
        leiningen.lein-common.lein-utils)
  (:require [leiningen.help    :as lhelp]
            [leiningen.clean   :as lclean]
            [leiningen.compile :as lcompile]
            [robert.hooke      :as hooke]))

(defn- once
  "Compiles the scss files once"
  [options]
  (println (str "Compiling scss files located in " (:src options)))
  (render-all! options false))

(defn- auto
  "Automatically recompiles when files are modified"
  [options]
  (println (str "Ready to compile scss files located in " (:src options)))
  (flush)
  (render-all! options true))

(defn- clean
  "Removes the autogenerated files"
  [options]
  (println "Deleting files generated by lein-scss.")
  (clean-all! options))

;; Leiningen tasks
(defn scss
  "Compiles scss files."
  {:help-arglists '([once auto clean])
   :subtasks [#'once #'auto #'clean]}
  ([project]
     (exit-failure (lhelp/help-for "scss")))

  ([project subtask & args]
     (let [options (extract-options :scss project)]
       (case subtask
         "once"  (once options)
         "auto"  (auto options)
         "clean" (clean options)
         (task-not-found subtask)))))


;; Hooks stuffs
(defmacro hook [task subtask args]
  `(let [options# (extract-options :scss (first ~args))]
     (apply ~task ~args)
     (when-not (~subtask (:ignore-hooks options#))
       (~(symbol (name subtask)) options#))))

(defn- compile-hook [task & args]
  (hook task :once args))

(defn- clean-hook [task & args]
  (hook task :clean args))

(hooke/add-hook #'lcompile/compile #'compile-hook)
(hooke/add-hook #'lclean/clean #'clean-hook)
